# Shell variables
# Generated by 'wal'
wallpaper='wallpaper.png'

# Special
background='#272727'
foreground='#d6b5a0'
cursor='#d6b5a0'

# Colors
color0='#272727'
color1='#455158'
color2='#565056'
color3='#495a5f'
color4='#4b707a'
color5='#5d635e'
color6='#737470'
color7='#d6b5a0'
color8='#9c8474'
color9='#455158'
color10='#565056'
color11='#495a5f'
color12='#4b707a'
color13='#5d635e'
color14='#737470'
color15='#d6b5a0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
